modLoader="javafml"
loaderVersion="[2,)"
license="MIT License https://github.com/McJtyMods/RFToolsBase/blob/1.16/LICENCE"
issueTrackerURL="http://github.com/McJtyMods/RFToolsBase/issues"
displayURL="http://github.com/McJtyMods/RFToolsBase/"
#logoFile="examplemod.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="McJty"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[mods]]
modId="rftoolsbase"
version="${file.jarVersion}"
displayName="RFToolsBase"
#updateJSONURL="http://myurl.me/" #optional
description='''
The base class for all RFTools tech mods (and XNet/Deep Resonance)
'''
[[dependencies.rftoolsbase]]
    modId="neoforge"
    type="required"
    versionRange="[21.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.rftoolsbase]]
    modId="mcjtylib"
    mandatory=true
    versionRange="[1.21-9.0.0,)"
    ordering="AFTER"
    side="BOTH"